### ISSUE TITLE
`use nix` or `use_nix`

### ISSUE THREAD

**Issue by DamienCassou** [nix-dot-dev/getting-started-nix-template#9]
I usually have `use_nix` in my `.envrc` files and this works well for me. I installed [nix-direnv](https://github.com/nix-community/nix-direnv) through a dedicated [option in home-manager](https://rycee.gitlab.io/home-manager/options.html#opt-programs.direnv.enableNixDirenvIntegration).

I see that this template has `use nix` instead of `use_nix` and this doesn't work for me: a change to the shell.nix file is not reflected in the environment.

**Comment by domenkozar** [comment]
This came up a few times now so I'll have to add some notes about it.

In general I prefer `use nix` because it's more reliant - you know you have to reenter the environment on change.

lorri and nix-direnv both have their own issues with reliability (so I've been told, I never tried either) and I think that's inferior to a simple action of knowing when to reload.

**Comment by DamienCassou** [comment]
Domen Kožar <notifications@github.com> writes:
> This came up a few times now so I'll have to add some notes about it.

Can you please explain:

- if anything needs to be installed for this to work, and
- the difference between other approaches?

Thank you

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by domenkozar** [comment]
This template uses https://devenv.sh so .envrc integration should be improved there
